require('dotenv').config();
const mongoose = require('mongoose');

const MONGO_URI = process.env.MONGO_URI || process.env.MONGO_URL || 'mongodb://127.0.0.1:27017/kyroz';
const USER_ID = '69f5e3b052f7bf6a6d934ef4';

const SopSchema = new mongoose.Schema({
  userId: mongoose.Schema.Types.ObjectId,
  title: String,
  category: String,
  contentEn: String,
  contentHi: String,
}, { timestamps: true });

const Sop = mongoose.model('Sop', SopSchema);

const sops = [
  {
    title: 'INSTANT DOSA SOP',
    category: 'South Indian',
    contentEn: '1. Dosa Batter Preparation\n\nS-301 Coastal Crust to Water Ratio: 1 kg S-301 Coastal Crust = 1.5 to 1.6 litres RO water.\nMixing: Take S-301 Coastal Crust in a clean large bowl. Slowly add RO water while continuously whisking.\nZero Lumps Rule: Ensure there are no lumps in the batter. It must be completely smooth.\nResting Period: Cover the batter and let it rest for 15–20 minutes. This allows semolina and rice flour to absorb water properly.\nFinal Check: After 20 minutes, if the batter feels too thick, add 50 ml water. The consistency should be pourable (not too thick, not too thin).\n\n2. Cooking Steps\n\nHeat the tawa. Sprinkle a little water on it. If it evaporates instantly with a “shhh” sound, the tawa is ready.\nBefore making each dosa, wipe the tawa with a wet cloth to reduce excess heat.\nPour one ladle of batter in the center and spread in a circular motion from inside to outside.\nWhen the dosa starts drying, add 1 spoon oil or butter around the edges and center.\nCook on medium flame until the dosa leaves the edges on its own and turns golden brown.\n\n3. Troubleshooting\n\nDosa sticking: Tawa is too hot. Sprinkle water to cool it down.\nDosa not spreading: Batter is too thick. Add 2–3 spoons of RO water.\nDosa not crispy: Tawa is cold or dosa was removed too early. Cook longer on medium flame.\nDosa tearing in center: Batter is old or not rested properly. Always rest for 15 minutes.\nNo golden color: Heat distribution is uneven. Adjust the flame properly.\n\n4. Helper & Chef-less Kitchen Advice\n\nFollow FIFO (First In First Out). Use older batter first.\nUse a fixed ladle size for consistent dosa size.\nClean the tawa every 5–10 dosas with salt water.\nSince S-301 has no cornstarch, sticking depends only on proper temperature control.\nAlways use clean and dry utensils.\n\n5. Storage Instructions\n\nStore S-301 Coastal Crust in a cool and dry place.\nAfter opening, keep it in an airtight container.\nLeftover batter should be stored in the refrigerator and mixed properly before reuse.',
    contentHi: '1. डोसा बैटर तैयार करना\n\nS-301 Coastal Crust और पानी का अनुपात: 1 किलो S-301 Coastal Crust = 1.5 से 1.6 लीटर RO पानी।\nमिक्सिंग: एक बड़े साफ बर्तन में S-301 Coastal Crust लें। धीरे-धीरे RO पानी डालते हुए लगातार फेंटें।\nZero Lumps Rule: बैटर में कोई गांठ नहीं होनी चाहिए। बैटर पूरी तरह स्मूद होना चाहिए।\nResting Period: बैटर को ढककर 15–20 मिनट के लिए छोड़ दें ताकि सूजी और चावल का आटा पानी अच्छी तरह सोख सके।\nFinal Check: 20 मिनट बाद यदि बैटर ज्यादा गाढ़ा लगे तो 50 ml पानी मिलाएं। बैटर की consistency डालने योग्य होनी चाहिए।\n\n2. डोसा बनाने की प्रक्रिया\n\nतवा गरम करें। थोड़ा पानी छिड़कें। यदि तुरंत “श्श्श” की आवाज के साथ सूख जाए तो तवा तैयार है।\nहर डोसा बनाने से पहले तवे को गीले कपड़े से पोंछें ताकि अतिरिक्त गर्मी कम हो जाए।\nबीच में एक करछी बैटर डालें और गोल-गोल घुमाते हुए फैलाएं।\nजब डोसा सूखने लगे तो किनारों और बीच में तेल या बटर डालें।\nमध्यम आंच पर तब तक पकाएं जब तक डोसा किनारों से खुद न छूट जाए और सुनहरा भूरा न हो जाए।\n\n3. समस्या समाधान\n\nडोसा चिपक रहा है: तवा बहुत ज्यादा गरम है। पानी छिड़ककर तापमान कम करें।\nडोसा फैल नहीं रहा: बैटर ज्यादा गाढ़ा है। 2–3 चम्मच RO पानी मिलाएं।\nडोसा क्रिस्पी नहीं है: तवा ठंडा है या जल्दी निकाल लिया। मध्यम आंच पर थोड़ा और पकाएं।\nबीच से फट रहा है: बैटर पुराना है या आराम नहीं दिया गया। 15 मिनट आराम देना जरूरी है।\nरंग नहीं आ रहा: तवे पर गर्मी बराबर नहीं है। आंच को सही करें।\n\n4. सहायक के लिए सुझाव\n\nFIFO नियम अपनाएं। पहले बना बैटर पहले इस्तेमाल करें।\nहर डोसे के लिए एक ही साइज की करछी रखें।\nहर 5–10 डोसे के बाद नमक वाले पानी से तवा साफ करें।\nS-301 में कॉर्नस्टार्च नहीं है, इसलिए चिपकना केवल तापमान पर निर्भर करेगा।\nहमेशा साफ और सूखे बर्तनों का उपयोग करें।\n\n5. स्टोरेज निर्देश\n\nS-301 Coastal Crust को ठंडी और सूखी जगह पर रखें।\nपैकेट खुलने के बाद एयरटाइट कंटेनर में रखें।\nबचा हुआ बैटर फ्रिज में रखें और दोबारा उपयोग से पहले अच्छी तरह मिलाएं।'
  },
  {
    title: 'INSTANT RICE IDLI SOP',
    category: 'South Indian',
    contentEn: '1. Pre-Cooking Preparation\n\nAlways use fresh RO water.\nLightly grease the idli moulds with oil so the idlis do not stick.\nCritical Rule: Do NOT add salt while preparing the batter. Salt is already included in S-305 STEAM CLOUD.\n\n2. Mixing Ratio\n\n1 kg S-305 STEAM CLOUD + 1.2 to 1.3 litres RO water = 45–50 idlis\n500 grams S-305 STEAM CLOUD + 600 to 650 ml RO water = 22–25 idlis\n200 grams S-305 STEAM CLOUD + 250 ml RO water = 8–10 idlis\n\n3. Mixing & Steaming Steps\n\nTake S-305 STEAM CLOUD in a large bowl and gradually add water while mixing.\nBatter should be thicker than dosa batter.\nCover and let the batter rest for 15 minutes.\nThis resting time helps rice flour and poha powder absorb water, making the idlis soft and spongy.\nFill the idli moulds but do not fill them to the top because the idlis will rise.\nBoil water in the steamer.\nOnce steam starts forming, place the idli stand inside.\nSteam on medium-high flame for 10–12 minutes.\nAfter switching off the flame, wait 2 minutes before removing the stand.\nUse a spoon dipped in water to remove the idlis.\n\n4. Troubleshooting\n\nHard Idli: Water was less or batter was not rested properly. Let batter rest for 15 minutes.\nFlat Idli: Too much water in batter. Reduce water next time.\nSticky Idli: Oil was not applied or idlis were removed too early. Grease moulds properly.\nIdli Not White: Dirty water or overcooking. Always use clean RO water.\n\n5. Helper Advice\n\nPrepare only the quantity needed for 1–2 hours.\nCold idlis can be reheated in the steamer.\nUse a toothpick test: if it comes out clean, idli is cooked.\nStore S-305 STEAM CLOUD in an airtight container.',
    contentHi: '1. पकाने से पहले की तैयारी\n\nहमेशा ताजा RO पानी का उपयोग करें।\nइडली के सांचों पर हल्का तेल लगाएं ताकि इडली चिपके नहीं।\nमहत्वपूर्ण नियम: बैटर बनाते समय नमक बिल्कुल न डालें। नमक पहले से S-305 STEAM CLOUD में मौजूद है।\n\n2. मिक्सिंग अनुपात\n\n1 किलो S-305 STEAM CLOUD + 1.2 से 1.3 लीटर RO पानी = 45–50 इडली\n500 ग्राम S-305 STEAM CLOUD + 600 से 650 ml RO पानी = 22–25 इडली\n200 ग्राम S-305 STEAM CLOUD + 250 ml RO पानी = 8–10 इडली\n\n3. मिक्सिंग और स्टीमिंग प्रक्रिया\n\nबड़े बर्तन में S-305 STEAM CLOUD लें और धीरे-धीरे पानी मिलाते जाएं।\nबैटर डोसा बैटर से थोड़ा गाढ़ा होना चाहिए।\nबैटर को ढककर 15 मिनट के लिए छोड़ दें।\nइससे चावल का आटा और पोहा पाउडर पानी सोख लेते हैं और इडली स्पंजी बनती है।\nइडली के सांचे भरें लेकिन ऊपर तक न भरें क्योंकि इडली फूलती है।\nस्टीमर में पानी उबालें।\nभाप बनने पर इडली स्टैंड अंदर रखें।\nमध्यम-तेज आंच पर 10–12 मिनट स्टीम करें।\nगैस बंद करने के बाद 2 मिनट इंतजार करें।\nपानी में डुबोए हुए चम्मच से इडली निकालें।\n\n4. समस्या समाधान\n\nइडली सख्त है: पानी कम था या बैटर को आराम नहीं दिया गया। 15 मिनट आराम दें।\nइडली बैठ गई: पानी ज्यादा हो गया। अगली बार कम पानी डालें।\nइडली चिपक रही है: तेल नहीं लगाया या जल्दी निकाली। सांचे में तेल लगाएं।\nइडली सफेद नहीं है: गंदा पानी या ज्यादा पक गई। साफ RO पानी इस्तेमाल करें।\n\n5. सहायक के लिए सुझाव\n\nउतनी ही इडली बनाएं जितनी 1–2 घंटे में उपयोग हो जाए।\nठंडी इडली को दोबारा स्टीमर में गर्म किया जा सकता है।\nटूथपिक टेस्ट करें। यदि साफ निकले तो इडली तैयार है।\nS-305 STEAM CLOUD को एयरटाइट कंटेनर में रखें।'
  },
  {
    title: 'INSTANT COCONUT CHUTNEY SOP',
    category: 'South Indian',
    contentEn: '1. Preparation\n\nAlways use cold RO water for making chutney. This keeps the coconut flavor fresh.\nCritical Rule: Do NOT add salt while mixing the chutney or during tempering. Salt is already included in S-307 KERALA KERNEL.\n\n2. Mixing Ratio\n\n1 kg S-307 KERALA KERNEL + 2.5 litres cold RO water = Approx. 3.5 kg chutney\n500 grams S-307 KERALA KERNEL + 1.25 litres cold RO water = Approx. 1.7 kg chutney\n100 grams S-307 KERALA KERNEL + 250 ml cold RO water = Approx. 350 grams chutney\n\n3. Mixing Steps\n\nTake the required quantity of S-307 KERALA KERNEL powder in a clean bowl.\nAdd cold RO water gradually while mixing continuously with a whisk or spoon.\nLet the chutney rest for 10–15 minutes.\nThis allows the desiccated coconut to absorb water and gives a fresh coconut-like texture.\nAfter resting, if the chutney feels too thick, add a little more water to adjust consistency.\n\n4. Fresh Tempering (Tadka)\n\nHeat 1–2 spoons oil in a small pan.\nAdd mustard seeds, 1–2 whole red chillies, and 8–10 fresh curry leaves.\nOnce the mustard seeds start crackling, pour the tempering over the prepared chutney.\nMix lightly.\n\n5. Troubleshooting\n\nChutney too thin: Too much water added. Add some more S-307 KERALA KERNEL powder and let it rest for 5 minutes.\nTaste too bland: Too much water added. Follow measurement chart properly next time.\nYellow/black color: Hot water used or chutney left uncovered. Always use cold water and refrigerate.\nDry texture: Resting time was skipped. Always rest for at least 10 minutes.\n\n6. Helper Advice\n\nPrepare chutney in small batches 2–3 times a day for freshness.\nAlways store chutney in the refrigerator.\nWhile serving, ensure a little tadka is visible in every portion.',
    contentHi: '1. तैयारी\n\nचटनी बनाने के लिए हमेशा ठंडा RO पानी इस्तेमाल करें। इससे नारियल का स्वाद ताजा रहता है।\nमहत्वपूर्ण नियम: चटनी बनाते समय या तड़का लगाते समय नमक बिल्कुल न डालें। नमक पहले से S-307 KERALA KERNEL में मौजूद है।\n\n2. मिक्सिंग अनुपात\n\n1 किलो S-307 KERALA KERNEL + 2.5 लीटर ठंडा RO पानी = लगभग 3.5 किलो चटनी\n500 ग्राम S-307 KERALA KERNEL + 1.25 लीटर ठंडा RO पानी = लगभग 1.7 किलो चटनी\n100 ग्राम S-307 KERALA KERNEL + 250 ml ठंडा RO पानी = लगभग 350 ग्राम चटनी\n\n3. मिक्सिंग प्रक्रिया\n\nसाफ बर्तन में आवश्यक मात्रा में S-307 KERALA KERNEL पाउडर लें।\nधीरे-धीरे ठंडा RO पानी डालते हुए लगातार whisk या चम्मच से मिलाएं।\nचटनी को 10–15 मिनट के लिए छोड़ दें।\nइससे सूखा नारियल पानी सोख लेता है और चटनी ताजे नारियल जैसी बनती है।\nयदि चटनी ज्यादा गाढ़ी लगे तो थोड़ा और पानी मिलाकर consistency सही करें।\n\n4. ताजा तड़का\n\nछोटे पैन में 1–2 चम्मच तेल गरम करें।\nइसमें राई, 1–2 साबुत लाल मिर्च और 8–10 ताजे करी पत्ते डालें।\nजब राई चटकने लगे तो यह तड़का चटनी के ऊपर डाल दें।\nहल्का सा मिला दें।\n\n5. समस्या समाधान\n\nचटनी पतली है: पानी ज्यादा हो गया। थोड़ा और S-307 KERALA KERNEL पाउडर डालें और 5 मिनट छोड़ दें।\nस्वाद फीका है: पानी ज्यादा हो गया। अगली बार सही माप का पालन करें।\nरंग पीला/काला हो गया: गरम पानी इस्तेमाल किया या खुला छोड़ दिया। हमेशा ठंडा पानी इस्तेमाल करें और फ्रिज में रखें।\nTexture सूखा है: Resting नहीं दिया। कम से कम 10 मिनट का आराम जरूरी है।\n\n6. सहायक के लिए सुझाव\n\nताजगी बनाए रखने के लिए दिन में 2–3 बार थोड़ी-थोड़ी मात्रा में चटनी बनाएं।\nचटनी हमेशा फ्रिज में रखें।\nसर्व करते समय हर हिस्से में थोड़ा तड़का दिखना चाहिए।'
  },
  {
    title: 'INSTANT MEDU VADA SOP',
    category: 'South Indian',
    contentEn: '1. Preparation\n\nAlways use fresh RO water.\nAlways use fresh refined oil for frying.\nCritical Rule: Do NOT add salt while preparing the batter. Salt is already included in S-304 CRUNCH CORE.\n\n2. Mixing Ratio\n\n1 kg S-304 CRUNCH CORE + 800–900 ml RO water = Thick batter\n500 grams S-304 CRUNCH CORE + 400–450 ml RO water = Thick batter\n\n3. Cooking Steps\n\nMix S-304 CRUNCH CORE with water to prepare a thick batter.\nCover and let the batter rest for 20 minutes.\nThis allows urad dal flour to absorb water and makes the batter lighter.\nBefore frying, beat the batter in one direction for 2–3 minutes.\nThis helps make the vada soft and spongy from inside.\nWet your hands, take a small portion of batter, make a hole in the center, and carefully place it in hot oil.\nA Medu Vada Maker machine can also be used.\nFry on medium flame until golden brown.\n\n4. Troubleshooting\n\nVada absorbing too much oil: Too much water in batter or oil is not hot enough. Add more S-304 CRUNCH CORE and increase oil temperature.\nVada hard: Batter was not beaten properly. Beat for 2–3 minutes before frying.\nShape not forming: Batter is too soft. Refrigerate for 10–15 minutes or add more premix.\nRaw inside: Flame was too high. Always fry on medium flame.\n\n5. Helper Advice\n\nFor extra crispiness, add 1 spoon hot oil to the batter while mixing.\nTest the batter by dropping a little in water. If it floats, batter is ready.\nServe hot with sambhar and coconut chutney.',
    contentHi: '1. तैयारी\n\nहमेशा ताजा RO पानी का उपयोग करें।\nतलने के लिए हमेशा ताजा रिफाइंड तेल का उपयोग करें।\nमहत्वपूर्ण नियम: बैटर बनाते समय नमक बिल्कुल न डालें। नमक पहले से S-304 CRUNCH CORE में मौजूद है।\n\n2. मिक्सिंग अनुपात\n\n1 किलो S-304 CRUNCH CORE + 800–900 ml RO पानी = गाढ़ा बैटर\n500 ग्राम S-304 CRUNCH CORE + 400–450 ml RO पानी = गाढ़ा बैटर\n\n3. बनाने की प्रक्रिया\n\nS-304 CRUNCH CORE में पानी मिलाकर गाढ़ा बैटर तैयार करें।\nबैटर को ढककर 20 मिनट के लिए छोड़ दें।\nइससे उड़द दाल का आटा पानी सोख लेता है और बैटर हल्का बनता है।\nतलने से पहले बैटर को एक ही दिशा में 2–3 मिनट तक अच्छी तरह फेंटें।\nइससे वड़ा अंदर से मुलायम और स्पंजी बनता है।\nहाथों को गीला करें, थोड़ा बैटर लें, बीच में छेद बनाएं और धीरे से गरम तेल में डालें।\nMedu Vada Maker मशीन का भी उपयोग किया जा सकता है।\nमध्यम आंच पर सुनहरा भूरा होने तक तलें।\n\n4. समस्या समाधान\n\nवड़ा ज्यादा तेल सोख रहा है: बैटर में पानी ज्यादा है या तेल पर्याप्त गरम नहीं है। थोड़ा और S-304 CRUNCH CORE डालें और तेल की गर्मी बढ़ाएं।\nवड़ा सख्त है: बैटर ठीक से नहीं फेंटा गया। तलने से पहले 2–3 मिनट अच्छी तरह फेंटें।\nआकार नहीं बन रहा: बैटर ज्यादा नरम है। 10–15 मिनट फ्रिज में रखें या थोड़ा और प्रीमिक्स डालें।\nअnder से कच्चा है: आंच बहुत तेज थी। हमेशा मध्यम आंच पर तलें।\n\n5. सहायक के लिए सुझाव\n\nअतिरिक्त क्रिस्पीनेस के लिए बैटर में 1 चम्मच गरम तेल मिलाएं।\nथोड़ा बैटर पानी में डालकर टेस्ट करें। यदि ऊपर तैरता है तो बैटर तैयार है।\nसांभर और नारियल चटनी के साथ गरमा-गरम सर्व करें।'
  },
  {
    title: 'ONION RAVA DOSA SOP',
    category: 'South Indian',
    contentEn: '1. Pre-Cooking Preparation\n\nRava dosa batter should be much thinner than regular dosa batter.\nThe consistency should be similar to buttermilk or milk.\nKeep finely chopped onion, green chilli, and fresh coriander ready separately.\nCritical Rule: Do NOT add salt while preparing the batter. Salt is already included in S-303 RAVA PEARL.\n\n2. Mixing Ratio\n\n1 kg S-303 RAVA PEARL + 2.5 to 3 litres RO water = Very thin batter\n200 grams S-303 RAVA PEARL + 500 to 600 ml RO water = Pouring consistency\n\n3. Cooking Steps\n\nMix S-303 RAVA PEARL with water and let it rest for 15–20 minutes.\nThis allows semolina to absorb water properly.\nThe tawa should be extremely hot (smoking hot).\nIf the tawa is not hot enough, the net texture will not form.\nAdd a little oil to the tawa and sprinkle finely chopped onion and curry leaves.\nTake batter in a bowl or ladle and pour it from the edges toward the center in a scattered pattern.\nDo NOT spread the batter like regular dosa.\nJust fill empty spaces while pouring.\nAdd 1–2 spoons oil or ghee around the edges.\nCook slowly until it becomes golden brown and leaves the edges naturally.\nNo need to flip the dosa.\n\n4. Troubleshooting\n\nNet texture not forming: Tawa is not hot enough or batter is too thick. Heat the tawa more or add water.\nDosa breaking: Batter is too thin. Add 1–2 spoons S-303 RAVA PEARL powder.\nDosa soft: Removed too early or flame too low. Cook longer on medium-high flame.\nSticking to tawa: Tawa not clean or less oil used. Clean tawa and apply oil properly.\n\n5. Helper Advice\n\nStir the batter before every dosa because semolina settles at the bottom.\nRava dosa takes 3–4 minutes to cook properly.\nDo not rush if you want crisp texture.\nServe open or folded in triangle shape to show the net texture.',
    contentHi: '1. पकाने से पहले की तैयारी\n\nरवा डोसा का बैटर सामान्य डोसा बैटर से बहुत पतला होना चाहिए।\nइसकी consistency छाछ या दूध जैसी होनी चाहिए।\nबारीक कटा प्याज, हरी मिर्च और ताजा धनिया अलग से तैयार रखें।\nमहत्वपूर्ण नियम: बैटर बनाते समय नमक बिल्कुल न डालें। नमक पहले से S-303 RAVA PEARL में मौजूद है।\n\n2. मिक्सिंग अनुपात\n\n1 किलो S-303 RAVA PEARL + 2.5 से 3 लीटर RO पानी = बहुत पतला बैटर\n200 ग्राम S-303 RAVA PEARL + 500 से 600 ml RO पानी = डालने योग्य consistency\n\n3. बनाने की प्रक्रिया\n\nS-303 RAVA PEARL को पानी के साथ मिलाकर 15–20 मिनट के लिए छोड़ दें।\nइससे सूजी पानी अच्छी तरह सोख लेती है।\nतवा बहुत ज्यादा गरम (स्मोकिंग हॉट) होना चाहिए।\nयदि तवा पर्याप्त गरम नहीं होगा तो जालीदार texture नहीं बनेगा।\nतवे पर थोड़ा तेल डालें और बारीक कटा प्याज तथा करी पत्ता छिड़कें।\nकटोरी या करछी में बैटर लें और किनारों से बीच की तरफ छिड़कते हुए डालें।\nइसे सामान्य डोसा की तरह फैलाना नहीं है।\nकेवल खाली जगह भरनी है।\nकिनारों पर 1–2 चम्मच तेल या घी डालें।\nधीरे-धीरे पकाएं जब तक सुनहरा भूरा न हो जाए और किनारों से खुद न छूट जाए।\nडोसा पलटने की जरूरत नहीं है।\n\n4. समस्या समाधान\n\nजाली नहीं बन रही: तवा पर्याप्त गरम नहीं है या बैटर गाढ़ा है। तवा और गरम करें या पानी मिलाएं।\nडोसा टूट रहा है: बैटर बहुत पतला है। 1–2 चम्मच S-303 RAVA PEARL पाउडर मिलाएं।\nडोसा नरम है: जल्दी निकाल लिया या आंच कम थी। मध्यम-तेज आंच पर ज्यादा देर पकाएं।\nतवे पर चिपक रहा है: तवा साफ नहीं है या तेल कम है। तवा साफ करें और सही मात्रा में तेल लगाएं।\n\n5. सहायक के लिए सुझाव\n\nहर डोसा बनाने से पहले बैटर हिलाएं क्योंकि सूजी नीचे बैठ जाती है।\nरवा डोसा को ठीक से पकने में 3–4 मिनट लगते हैं।\nक्रिस्पी texture के लिए जल्दबाजी न करें।\nजालीदार texture दिखाने के लिए खुला या त्रिकोण आकार में सर्व करें।'
  },
  {
    title: 'INSTANT RED (KARA) CHUTNEY SOP',
    category: 'South Indian',
    contentEn: '1. Preparation\n\nAlways use lukewarm RO water for making this chutney.\nLukewarm water helps onion powder and tomato powder hydrate properly.\nCritical Rule: Do NOT add salt while mixing the chutney. Salt is already included in S-306 TANGY TROPIC.\n\n2. Mixing Ratio\n\n1 kg S-306 TANGY TROPIC + 2.5 litres lukewarm RO water = Approx. 3.5 kg chutney\n500 grams S-306 TANGY TROPIC + 1.25 litres lukewarm RO water = Approx. 1.7 kg chutney\n100 grams S-306 TANGY TROPIC + 250 ml lukewarm RO water = Approx. 350 grams chutney\n\n3. Mixing Steps\n\nTake the required quantity of S-306 TANGY TROPIC powder in a clean bowl.\nSlowly add lukewarm RO water while continuously whisking.\nMix until the chutney becomes completely smooth without lumps.\nCover and let it rest for 15 minutes.\nThis helps tomato powder, garlic flavor, and dal powder settle properly.\nIf the chutney becomes too thick after resting, add a little more water.\nThis chutney should be slightly thicker than coconut chutney.\n\n4. Fresh Tempering (Tadka)\n\nHeat 2 spoons oil in a small pan.\nAdd mustard seeds, a little split urad dal, and 8–10 fresh curry leaves.\nFry until urad dal turns light golden brown and mustard seeds crackle.\nPour the tempering over the chutney.\n\n5. Troubleshooting\n\nChutney looks pale: Cold water used or resting time skipped. Use lukewarm water and rest properly.\nToo spicy: Too much S-306 TANGY TROPIC added. Add a little sugar or tomato powder.\nWater separating: Mixing was not proper. Whisk strongly for 1–2 minutes.\nToo salty: Less water added. Add more lukewarm water to balance.\n\n6. Helper Advice\n\nThis chutney should have a spicy and tangy flavor.\nIf customers prefer less spicy food, serve more coconut chutney.\nFor best taste, prepare fresh daily and store in refrigerator.\nProper presentation with visible urad dal and curry leaves makes it look premium.',
    contentHi: '1. तैयारी\n\nइस चटनी के लिए हमेशा गुनगुना RO पानी इस्तेमाल करें।\nगुनगुना पानी प्याज पाउडर और टमाटर पाउडर को अच्छी तरह hydrate करने में मदद करता है।\nमहत्वपूर्ण नियम: चटनी बनाते समय नमक बिल्कुल न डालें। नमक पहले से S-306 TANGY TROPIC में मौजूद है।\n\n2. मिक्सिंग अनुपात\n\n1 किलो S-306 TANGY TROPIC + 2.5 लीटर गुनगुना RO पानी = लगभग 3.5 किलो चटनी\n500 ग्राम S-306 TANGY TROPIC + 1.25 लीटर गुनगुना RO पानी = लगभग 1.7 किलो चटनी\n100 ग्राम S-306 TANGY TROPIC + 250 ml गुनगुना RO पानी = लगभग 350 ग्राम चटनी\n\n3. मिक्सिंग प्रक्रिया\n\nसाफ बर्तन में आवश्यक मात्रा में S-306 TANGY TROPIC पाउडर लें।\nधीरे-धीरे गुनगुना RO पानी डालते हुए लगातार whisk करें।\nतब तक मिलाएं जब तक चटनी पूरी तरह स्मूद और बिना गांठ की न हो जाए।\nढककर 15 मिनट के लिए छोड़ दें।\nइससॆ टमाटर पाउडर, लहसुन फ्लेवर और दाल पाउडर अच्छी तरह सेट हो जाते हैं।\nयदि चटनी ज्यादा गाढ़ी हो जाए तो थोड़ा और पानी मिलाएं।\nयह चटनी नारियल चटनी से थोड़ी ज्यादा गाढ़ी होनी चाहिए।\n\n4. ताजा तड़का\n\nछोटे पैन में 2 चम्मच तेल गरम करें।\nइसमें राई, थोड़ी उड़द दाल और 8–10 ताजे करी पत्ते डालें।\nउड़द दाल हल्की सुनहरी होने तक और राई चटकने तक भूनें।\nयह तड़का चटनी के ऊपर डाल दें।\n\n5. समस्या समाधान\n\nचटनी फीकी दिख रही है: ठंडा पानी इस्तेमाल किया या resting नहीं दिया। गुनगुना पानी इस्तेमाल करें।\nबहुत तीखी है: S-306 TANGY TROPIC ज्यादा डल गया। थोड़ी चीनी या टमाटर पाउडर मिलाएं।\nपानी अलग हो रहा है: ठीक से मिक्स नहीं हुई। 1–2 मिनट जोर से whisk करें।\nबहुत नमकीन है: पानी कम डाला गया। थोड़ा और गुनगुना पानी मिलाएं।\n\n6. सहायक के लिए सुझाव\n\nइस चटनी का स्वाद तीखा और खट्टा होना चाहिए।\nयदि ग्राहक कम तीखा पसंद करते हैं तो नारियल चटनी ज्यादा सर्व करें।\nबेहतर स्वाद के लिए रोज ताजा बनाएं और फ्रिज में रखें।\nऊपर दिखती उड़द दाल और करी पत्ता इसे प्रीमियम लुक देते हैं।'
  },
  {
    title: 'MASALA DOSA STUFFING (ALOO MASALA) SOP',
    category: 'South Indian',
    contentEn: '1. Pre-Cooking Preparation\n\nBoil 1 kg potatoes, peel them, and keep them ready.\nLightly mash the potatoes by hand.\nCritical Rule: Do NOT make the potatoes into a smooth paste. Small chunks should remain for better texture.\nImportant Rule: Do NOT add salt while boiling potatoes. Salt is already included in S-302 YELLOW TEMPER.\n\n2. Quantity Ratio\n\n1 kg boiled potatoes + 120 grams S-302 YELLOW TEMPER + 150 ml RO water + 2–3 tablespoons oil\n500 grams boiled potatoes + 60 grams S-302 YELLOW TEMPER + 75 ml RO water + 1.5 tablespoons oil\n250 grams boiled potatoes + 30 grams S-302 YELLOW TEMPER + 40 ml RO water + 1 tablespoon oil\n\n3. Cooking Steps\n\nHeat oil in a pan according to the required quantity.\nAdd S-302 YELLOW TEMPER to the hot oil.\nStir for 30–40 seconds only.\nDo not burn the masala. Mustard seeds should crackle and dal should turn slightly brown.\nImmediately add RO water.\nThe dehydrated onion and curry leaves will absorb water and form a thick masala paste.\nAdd mashed boiled potatoes.\nMix properly so the masala coats all potatoes evenly.\nCook on low flame for 2 minutes.\nSwitch off the flame.\nOptional: Add finely chopped fresh coriander for extra flavor.\n\n4. Troubleshooting\n\nMasala too dry: Water is less. Add 2–3 spoons warm RO water.\nToo salty: Potato quantity is less. Add 1–2 more boiled potatoes.\nMasala burnt: Oil was too hot or masala was roasted too long. Add water immediately next time.\nNot spreading on dosa: Stuffing is too thick. Add a little more water to make it semi-solid.\n\n5. Helper Advice\n\nPrepare only enough stuffing for the next 2–3 hours.\nOld potato stuffing affects taste quality.\nStore leftover stuffing in an airtight container in the refrigerator.\nStuffing consistency should be easy to spread without tearing the dosa.',
    contentHi: '1. पकाने से पहले की तैयारी\n\n1 किलो आलू उबालकर, छीलकर तैयार रखें।\nआलू को हाथ से हल्का मैश करें।\nमहत्वपूर्ण नियम: आलू को बिल्कुल पेस्ट न बनाएं। छोटे-छोटे टुकड़े रहने चाहिए ताकि अच्छा texture मिले।\nजरूरी नियम: आलू उबालते समय नमक बिल्कुल न डालें। नमक पहले से S-302 YELLOW TEMPER में मौजूद है।\n\n2. मात्रा अनुपात\n\n1 किलो उबले आलू + 120 ग्राम S-302 YELLOW TEMPER + 150 ml RO पानी + 2–3 टेबलस्पून तेल\n500 ग्राम उबले आलू + 60 ग्राम S-302 YELLOW TEMPER + 75 ml RO पानी + 1.5 टेबलस्पून तेल\n250 ग्राम उबले आलू + 30 ग्राम S-302 YELLOW TEMPER + 40 ml RO पानी + 1 टेबलस्पून तेल\n\n3. बनाने की प्रक्रिया\n\nआवश्यक मात्रा के अनुसार कढ़ाई में तेल गरम करें।\nगरम तेल में S-302 YELLOW TEMPER डालें।\nकेवल 30–40 सेकंड तक चलाएं।\nमसाला जलना नहीं चाहिए। राई चटकनी चाहिए और दाल हल्की भूरी होनी चाहिए।\nतुरंत RO पानी डालें।\nसूखा प्याज और करी पत्ता पानी सोखकर गाढ़ा मसाला पेस्ट बना देंगे।\nमैश किए हुए उबले आलू डालें।\nअच्छी तरह मिलाएं ताकि मसाला सभी आलुओं पर बराबर लग जाए।\nधीमी आंच पर 2 मिनट पकाएं।\nगैस बंद करें।\nवैकल्पिक: अतिरिक्त स्वाद के लिए बारीक कटा हरा धनिया डाल सकते हैं।\n\n4. समस्या समाधान\n\nमसाला बहुत सूखा है: पानी कम है। 2–3 चम्मच गरम RO पानी मिलाएं।\nबहुत नमकीन है: आलू कम हैं। 1–2 और उबले आलू मिलाएं।\nमसाला जल गया: तेल बहुत गरम था या ज्यादा देर भुना। अगली बार तुरंत पानी डालें।\nडोसा पर नहीं फैल रहा: stuffing ज्यादा गाढ़ी है। थोड़ा और पानी मिलाकर semi-solid बनाएं।\n\n5. सहायक के लिए सुझाव\n\nकेवल अगले 2–3 घंटे की जरूरत के हिसाब से stuffing बनाएं।\nपुरानी आलू stuffing स्वाद खराब करती है।\nबचा हुआ मसाला एयरटाइट कंटेनर में फ्रिज में रखें।\nstuffing ऐसी होनी चाहिए जो डोसा फाड़े बिना आसानी से फैल जाए।'
  },
  {
    title: 'PREMIUM SAMBHAR SOP',
    category: 'South Indian',
    contentEn: '1. Pre-Cooking Preparation\n\nCut fresh vegetables like bottle gourd (lauki), drumstick, and onion into large pieces.\nBoil the vegetables separately in RO water.\nCritical Rule: Do NOT add salt while boiling vegetables. Salt is already included in S-308 LENTIL LAVA.\n\n2. Mixing Ratio\n\n1 kg S-308 LENTIL LAVA + 9 litres RO water + 1.5 kg boiled vegetables = 10 litres sambhar\n500 grams S-308 LENTIL LAVA + 4.5 litres RO water + 750 grams boiled vegetables = 5 litres sambhar\n100 grams S-308 LENTIL LAVA + 900 ml RO water + 150 grams boiled vegetables = 1 litre sambhar\n\n3. Cooking Steps\n\nHeat the required quantity of RO water in a large vessel.\nSlowly add S-308 LENTIL LAVA while continuously whisking.\nMix until all lumps are completely removed.\nAdd the pre-boiled vegetables.\nBoil the sambhar on medium flame for 10–12 minutes.\nThis helps the dal powder and spices blend properly.\nIf sambhar becomes too thick, add hot RO water.\nNever add cold water.\n\n4. Fresh Tempering (Mandatory)\n\nHeat 2 spoons oil or ghee in a small pan.\nAdd mustard seeds, 2–3 whole red chillies, and 10–12 fresh curry leaves.\nOnce mustard seeds start crackling, pour the tempering into the sambhar.\nImmediately close the lid so the aroma stays inside.\n\n5. Troubleshooting\n\nToo salty: Water is less or vegetables had salt. Add hot RO water and a little jaggery.\nLess salty: Too much water added. Boil for 5–7 more minutes to reduce.\nLumps present: Premix was added in cold water. Use a hand blender or strain it.\nTaste bland: Sambhar was not boiled properly. Simmer for at least 10 minutes.\n\n6. Helper Advice\n\nEvery serving should have equal vegetables and dal ratio.\nAlways keep sambhar covered.\nDo not keep extra salt openly in the kitchen to avoid mistakes.\nServe piping hot for best taste.',
    contentHi: '1. पकाने से पहले की तैयारी\n\nताजी सब्जियां जैसे लौकी, सहजन (drumstick), और प्याज को बड़े टुकड़ों में काटें।\nसब्जियों को अलग से RO पानी में उबाल लें।\nमहत्वपूर्ण नियम: सब्जियां उबालते समय नमक बिल्कुल न डालें। नमक पहले से S-308 LENTIL LAVA में मौजूद है।\n\n2. मिक्सिंग अनुपात\n\n1 किलो S-308 LENTIL LAVA + 9 लीटर RO पानी + 1.5 किलो उबली सब्जियां = 10 लीटर सांभर\n500 ग्राम S-308 LENTIL LAVA + 4.5 लीटर RO पानी + 750 ग्राम उबली सब्जियां = 5  लीटर सांभर\n100 ग्राम S-308 LENTIL LAVA + 900 ml RO पानी + 150 grams उबली सब्जियां = 1 लीटर सांभर\n\n3. बनाने की प्रक्रिया\n\nबड़े बर्तन में आवश्यक मात्रा में RO पानी गरम करें।\nधीरे-धीरे S-308 LENTIL LAVA डालते हुए लगातार whisk करें।\nतब तक मिलाएं जब तक सारी गांठें खत्म न हो जाएं।\nपहले से उबली हुई सब्जियां डालें।\nमध्यम आंच पर 10–12 मिनट तक उबालें।\nइससे दाल पाउडर और मसाले अच्छी तरह मिल जाते हैं।\nयदि सांभर ज्यादा गाढ़ा हो जाए तो गरम RO पानी मिलाएं।\nकभी भी ठंडा पानी न डालें।\n\n4. ताजा तड़का (अनिवार्य)\n\nछोटे पैन में 2 चम्मच तेल या घी गरम करें।\nइसमें राई, 2–3 साबुत लाल मिर्च, और 10–12 ताजे करी पत्ते डालें।\nराई चटकने पर यह तड़का सांभर में डाल दें।\nतुरंत ढक्कन बंद कर दें ताकि खुशबू अंदर बनी रहे।\n\n5. समस्या समाधान\n\nबहुत नमकीन: पानी कम है या सब्जियों में नमक था। गरम RO पानी और थोड़ा गुड़ मिलाएं।\nनमक कम है: पानी ज्यादा है। 5–7 मिनट और उबालें।\nगांठें हैं: प्रीमिक्स ठंडे पानी में डाला गया। हैंड ब्लेंडर चलाएं या छान लें।\nस्वाद फीका है: सांभर ठीक से नहीं उबला। कम से कम 10 मिनट simmer करें।\n\n6. सहायक के लिए सुझाव\n\nहर सर्विंग में सब्जियों और दाल का अनुपात बराबर होना चाहिए।\nसांभर हमेशा ढककर रखें।\nगलती से अतिरिक्त नमक न पड़े, इसलिए खुला नमक किचन में न रखें।\nबेहतर स्वाद के लिए गरमा-गरम सर्व करें।'
  },
  {
    title: 'UTTAPAM SOP',
    category: 'South Indian',
    contentEn: '1. Pre-Cooking Preparation\n\nUse Kyroz S-305 STEAM CLOUD batter as the base.\nPrepare finely chopped onion, tomato, green chilli, and fresh coriander as toppings.\nMix all vegetables in a separate bowl.\nCritical Rule: Do NOT add salt to the batter or toppings. Salt is already included in S-305 STEAM CLOUD.\n\n2. Mixing Ratio\n\n1 kg S-305 STEAM CLOUD + 1.4 to 1.5 litres RO water = Thick but pourable batter\n500 grams S-305 STEAM CLOUD + 700 to 750 ml RO water = Semi-thick batter\n\n3. Cooking Steps\n\nMix S-305 STEAM CLOUD with RO water and let it rest for 15 minutes.\nThis helps the batter become soft and properly hydrated.\nHeat the tawa on medium flame (slightly less hot than dosa tawa).\nApply a little oil on the tawa.\nPour one large ladle of batter in the center.\nDo NOT spread it thin like dosa.\nKeep the uttapam thick.\nImmediately sprinkle the prepared vegetable toppings over the batter.\nPress the toppings lightly so they stick properly.\nAdd a little oil or butter around the edges and on top.\nCook until the bottom turns golden brown.\nFlip the uttapam.\nCook the toppings side for 1 minute until lightly roasted.\nFlip once again and serve hot.\n\n4. Troubleshooting\n\nRaw from inside: Batter too thick or flame too high. Add a little water and cook on low flame.\nToppings falling off: Toppings were not pressed properly or added too late. Add toppings immediately and press gently.\nNot spongy: Batter was not rested. Always rest for 15 minutes.\nSticking to tawa: Tawa too cold or less oil used. Check heat and oil properly.\n\n5. Helper Advice\n\nGolden brown color indicates proper cooking quality.\nVery white uttapam looks undercooked.\nUse the same bowl or ladle every time for consistent size.\nServe with both coconut chutney and red kara chutney for better customer experience.',
    contentHi: '1. पकाने से पहले की तैयारी\n\nबेस के लिए Kyroz S-305 STEAM CLOUD बैटर का उपयोग करें।\nबारीक कटा प्याज, टमाटर, हरी मिर्च और ताजा धनिया toppings के लिए तैयार रखें।\nसभी सब्जियों को अलग बाउल में मिलाकर रखें।\nमहत्वपूर्ण नियम: बैटर या toppings में नमक बिल्कुल न डालें। नमक पहले से S-305 STEAM CLOUD में मौजूद है।\n\n2. मिक्सिंग अनुपात\n\n1 किलो S-305 STEAM CLOUD + 1.4 से 1.5 लीटर RO पानी = गाढ़ा लेकिन डालने योग्य बैटर\n500 ग्राम S-305 STEAM CLOUD + 700 से 750 ml RO पानी = semi-thick बैटर\n\n3. बनाने की प्रक्रिया\n\nS-305 STEAM CLOUD को RO पानी के साथ मिलाकर 15 मिनट के लिए छोड़ दें।\nइससे बैटर अच्छी तरह hydrate होकर मुलायम बनता है।\nतवा मध्यम आंच पर गरम करें (डोसा तवे से थोड़ा कम गरम)।\nतवे पर थोड़ा तेल लगाएं।\nबीच में एक बड़ी करछी बैटर डालें।\nइसे डोसा की तरह पतला न फैलाएं।\nउत्तपम को मोटा रखें।\nतुरंत तैयार की हुई vegetable toppings ऊपर डालें।\nहल्के हाथ से दबाएं ताकि toppings अच्छी तरह चिपक जाएं।\nकिनारों और ऊपर थोड़ा तेल या बटर डालें।\nनीचे से सुनहरा भूरा होने तक पकाएं।\nउत्तपम को पलटें।\ntoppings वाली साइड को 1 minute तक हल्का roast करें।\nफिर दोबारा पलटकर गरमा-गरम सर्व करें।\n\n4. समस्या समाधान\n\nअंदर से कच्चा: बैटर ज्यादा गाढ़ा है या आंच तेज है। थोड़ा पानी मिलाएं और धीमी आंच पर पकाएं।\nToppings गिर रही हैं: ठीक से दबाई नहीं गईं या देर से डाली गईं। तुरंत डालकर हल्का दबाएं।\nस्पंजी नहीं है: बैटर को आराम नहीं दिया गया। हमेशा 15 मिनट rest दें।\nतवे पर चिपक रहा है: तवा ठंडा है या तेल कम है। सही तापमान और तेल का ध्यान रखें।\n\n5. सहायक के लिए सुझाव\n\nसुनहरा भूरा रंग सही cooking quality दर्शाता है।\nबहुत सफेद उत्तपम अधपका लगता है।\nहर बार एक ही बाउल या करछी का उपयोग करें ताकि size समान रहे।\nबेहतर customer experience के लिए नारियल chutney और रेड कारा चटनी दोनों के साथ सर्व करें।'
  },
  {
    title: 'DAILY OPERATIONAL CHART SOP',
    category: 'South Indian',
    contentEn: '1. Morning Setup & Pre-Preparation (8:00 AM – 10:00 AM)\n\nA. Batter Preparation\nPrepare dosa and idli batter and let them rest for 20 minutes.\nPrepare coconut chutney and red chutney and store them in the refrigerator.\nPrepare medu vada batter, beat it properly, and keep it in the refrigerator. Cold batter gives better shape.\n\nB. Vegetable Preparation\nAll cutting should be done once to avoid repeated work.\nSambhar vegetables: Cut bottle gourd, drumstick, and onion into 2-inch pieces, boil them, and refrigerate.\nAloo masala: Boil potatoes, peel them, mash them, and keep ready.\nToppings for uttapam/rava dosa: Prepare a mix of onion, tomato, green chilli, and coriander.\n\nC. Tadka Station\nKeep these items always ready:\nMustard seeds\nWhole red chillies\nCurry leaves\nOil/Ghee\nSplit urad dal\n\n2. Daily Station Setup\n\nDosa Station\nKeep ready:\nBatter bowl\nOil/Butter\nMug of water\nClean cloth for cooling the tawa\n\nSambhar Station\nKeep ready:\nSambhar base\nBoiled vegetables\nTadka pan\n\nSteam Station\nKeep ready:\nGreased idli stands\nMedu vada batter\nHot fryer oil\n\nPacking Station\nKeep ready:\n3-section plates/boxes\nChutney bowls\nSpoons\nNapkins\n\n3. Standard Daily Schedule\n\n10:30 AM: Check batter consistency and chutney quality.\n11:30 AM: Prepare first fresh batch of sambhar and aloo masala before lunch rush.\n4:00 PM: Prepare fresh medu vada batter and refill batter for evening snacks.\n9:30 PM (Closing):\nMove leftover batter to refrigerator\nDeep clean the tawa\nCheck premix stock for next day\n\n4. Owner Quality Audit\n\nSound Test: Water on tawa should make a “shhh” sound.\nVisual Test: Sambhar should look vibrant red and chutney should remain fresh in color.\nSmell Test: Kitchen should have aroma of curry leaves and mustard tempering.\nWaste Check: Monitor leftover batter to improve portion control.\n\n5. Special Chef-less Kitchen Rule\n\nNever allow approximate measurement.\nKeep standard measuring cups:\n250 ml\n500 ml\n1 litre\nFixed measurement ensures consistent taste every day.',
    contentHi: '1. सुबह की तैयारी और प्री-प्रेप (8:00 AM – 10:00 AM)\n\nA. बैटर तैयारी\nडोसा और इडली का बैटर तैयार करके 20 मिनट के लिए छोड़ दें।\nनारियल चटनी और रेड चटनी बनाकर फ्रिज में रखें।\nमेदु वड़ा बैटर तैयार करके अच्छी तरह फेंटें और फ्रिज में रखें। ठंडा बैटर बेहतर आकार देता है।\n\nB. सब्जियों की तैयारी\nबार-बार काम से बचने के लिए सारी कटिंग एक बार में करें।\nसांभर के लिए लौकी, सहजन और प्याज को 2 इंच टुकड़ों में काटकर उबालकर फ्रिज में रखें।\nआलू मसाला के लिए आलू उबालकर, छीलकर, मैश करके रखें।\nउत्तपम/रवा डोसा के लिए प्याज, टमाटर, हरी मिर्च और धनिया का मिश्रण तैयार रखें।\n\nC. तड़का स्टेशन\nहमेशा ये चीजें तैयार रखें:\nराई\nसाबुत लाल मिर्च\nकरी पत्ता\nतेल/घी\nउड़द दाल\n\n2. दैनिक स्टेशन सेटअप\n\nडोसा स्टेशन\nतैयार रखें:\nबैटर बाउल\nतेल/बटर\nपानी का मग\nतवा साफ करने के लिए साफ कपड़ा\n\nसांभर स्टेशन\nतैयार रखें:\nसांभर बेस\nउबली सब्जियां\nतड़का पैन\n\nस्टीम स्टेशन\nतैयार रखें:\nतेल लगे इडली स्टैंड\nमेदु वड़ा बैटर\nगरम फ्रायर तेल\n\nपैकिंग स्टेशन\nतैयार रखें:\n3-सेक्शन प्लेट/बॉक्स\nचटनी कटोरी\nचम्मच\nनैपकिन\n\n3. दैनिक समय-सारणी\n\n10:30 AM: बैटर consistency और चटनी की गुणवत्ता जांचें।\n11:30 AM: लंच rush से पहले ताजा सांभर और आलू मसाला तैयार करें।\n4:00 PM: शाम के snacks के लिए ताजा मेदु वड़ा बैटर तैयार करें।\n9:30 PM (बंद होने पर):\nबचा बैटर फ्रिज में रखें\nतवे की deep cleaning करें\nअगले दिन के premix stock की जांच करें\n\n4. मालिक की गुणवत्ता जांच\n\nSound Test: तवे पर पानी डालने पर “श्श्श” की आवाज आनी चाहिए।\nVisual Test: सांभर चमकदार लाल दिख होना चाहिए और चटनी ताजा रंग की होनी चाहिए।\nSmell Test: किचन में करी पत्ता और राई तड़के की खुशबू होनी चाहिए।\nWaste Check: बचे बैटर की मात्रा देखकर portion control सुधारें।\n\n5. विशेष Chef-less Kitchen नियम\n\nअनुमान से काम बिल्कुल न करें।\nStandard measuring cups रखें:\n250 ml\n500 ml\n1 लीटर\nतय माप हर दिन एक जैसा स्वाद सुनिश्चित करता है।'
  },
  {
    title: 'KITCHEN PRE-PREP & SETUP SOP',
    category: 'South Indian',
    contentEn: '1. Kitchen Pre-Preparation (Complete before 9:00 AM)\n\nStep 1: Hydration Station\nPrepare dosa, idli, and medu vada batter.\nCover the batter and allow proper resting time.\nPrepare both coconut chutney and red chutney.\nStore the chutneys in the refrigerator immediately.\n\nStep 2: Cutting Station\nPrepare all vegetables in advance to avoid delays during service.\nSambhar vegetables: Cut bottle gourd and drumstick into 2-inch pieces and boil them.\nPotatoes: Boil 5 kg potatoes, peel them, mash them, and refrigerate.\nToppings Mix: Prepare onion, tomato, coriander, and green chilli mixture.\n\nStep 3: Tadka Rack\nKeep the following items fully stocked:\nYellow/Black mustard seeds\nFresh curry leaves\nSplit urad dal (for crunch)\n\n2. Station-Wise Operational Cards\n\nA. Dosa & Uttapam Station\nClean the tawa with a wet cloth after every dosa.\nWater sprinkled on the tawa should make a “shhh” sound.\nFor uttapam, keep the batter thick and press the toppings properly.\n\nB. Sambhar & Chutney Station\nAlways use a whisk to avoid lumps.\nBoil sambhar for at least 10–12 minutes.\nImportant Warning: Kyroz premix already contains 100% salt. Do NOT add extra salt.\n\n3. Fryer & Steam Station\nGrease idli moulds before steaming.\nSteam idlis for 12 minutes.\nMaintain fryer oil temperature around 180°C for medu vada.\nBeat vada batter for 2 minutes before frying.\n\n4. Daily Audit Checklist (Owner/Manager)\n\nCheck these points every day:\nConsistency: Is the chutney and sambhar taste consistent with previous day?\nTemperature: Is sambhar served piping hot?\nHygiene: Is there any carbon layer or dirt on the tawa?\nWaste Control: Check how much batter remains at the end of the day and adjust next day preparation.',
    contentHi: '1. किचन प्री-प्रेपरेशन (सुबह 9:00 बजे से पहले पूरा करें)\n\nस्टेप 1: Hydration Station\nडोसा, इडली और मेदु वड़ा का बैटर तैयार करें।\nबैटर को ढककर सही समय तक आराम दें।\nनारियल चटनी और रेड चटनी तैयार करें।\nचटनियों को तुरंत फ्रिज में रखें।\n\nस्टेप 2: Cutting Station\nसर्विस के दौरान देरी से बचने के लिए सभी सब्जियां पहले से तैयार रखें।\nसांभर सब्जियां: लौकी और सहजन को 2 इंच टुकड़ों में काटकर उबाल लें।\nआलू: 5 किलो आलू उबालें, छीलें, मैश करें और फ्रिज में रखें।\nटॉपिंग मिक्स: प्याज, टमाटर, धनिया और हरी मिर्च का मिश्रण तैयार करें।\n\nस्टेप 3: तड़का रैक\nइन चीजों का स्टॉक हमेशा पूरा रखें:\nपीली/काली राई\nसाबुत सूखी लाल मिर्च\nताजे करी पत्ते\nउड़द दाल (क्रंच के लिए)\n\n2. स्टेशन-वाइज ऑपरेशनल निर्देश\n\nA. डोसा और उत्तपम स्टेशन\nहर डोसा के बाद तवे को गीले कपड़े से साफ करें।\nतवे पर पानी डालने पर “श्श्श” की आवाज आनी चाहिए।\nउत्तपम के लिए बैटर गाढ़ा रखें और toppings को अच्छे से दबाएं।\n\nB. सांभर और चटनी स्टेशन\nगांठों से बचने के लिए हमेशा whisk का उपयोग करें।\nसांभर को कम से कम 10–12 मिनट उबालें।\nमहत्वपूर्ण चेतावनी: Kyroz premix में पहले से 100% नमक है। अतिरिक्त नमक बिल्कुल न डालें।\n\nC. फ्रायर और स्टीम स्टेशन\nस्टीम करने से पहले इडली moulds में तेल लगाएं।\nइडली को 12 मिनट स्टीम करें।\nमेदु वड़ा के लिए तेल का तापमान लगभग 180°C रखें।\nतलने से पहले वड़ा बैटर को 2 मिनट तक फेंटें।\n\n3. दैनिक ऑडिट चेकलिस्ट (मालिक/मैनेजर)\n\nहर दिन ये बिंदु जांचें:\nConsistency: क्या चटनी और सांभर का स्वाद पिछले दिन जैसा है?\nTemperature: क्या सांभर गरमा-गरम सर्व हो रहा है?\nHygiene: क्या तवे पर कार्बन लेयर या गंदगी जमा है?\nWaste Control: दिन के अंत में बचा बैटर जांचें और अगले दिन की तैयारी उसी अनुसार करें।'
  }
];

mongoose.connect(MONGO_URI).then(async () => {
  console.log('Connected to MongoDB for seeding...');
  
  for (const sopData of sops) {
    await Sop.findOneAndUpdate(
      { title: sopData.title, userId: USER_ID },
      { ...sopData, userId: USER_ID },
      { upsert: true, new: true }
    );
    console.log(`Seeded SOP: ${sopData.title}`);
  }

  console.log('Seeding complete!');
  process.exit(0);
}).catch(err => {
  console.error('Seeding error:', err);
  process.exit(1);
});
